import React from 'react'
import Page from "/src/components/Page";
import { ManagePosts } from "/src/modules";
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <ManagePosts />
      </Page>
    </>
  )
}
